<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Profile</title>
  </head>
  <body>
    <table>
      <tr>
        <td>
          <table>
            <tr>
              <td>
                <img
                  src="static/images/house.png"
                  alt="house"
                  width="40"
                  height="40"
                />
              </td>
            </tr>
            <tr>
              <td>
                <img
                  src="static/images/profile.png"
                  alt="profile"
                  width="40"
                  height="40"
                />
              </td>
            </tr>
            <tr>
              <td>
                <img
                  src="static/images/plus.png"
                  alt="plus"
                  width="40"
                  height="40"
                />
              </td>
            </tr>
          </table>
        </td>
        <td>
          <div class="profile">
            <img
              src="static/images/avatar.jpg"
              alt="avatar"
              width="123"
              height="123"
            />
            <p>Ваня Денисов</p>
            <p>Привет! Я системный аналитик в ACME :) Тут моя</p>
            <p>жизнь только для самых классных!</p>
            <img src="static/images/number_post.png" alt="post" />
            <table>
              <tr>
                <td>
                  <img
                    src="static/images/street.png"
                    alt="street"
                    width="322"
                    height="322"
                  />
                </td>
                <td>
                  <img
                    src="static/images/houses.png"
                    alt="houses"
                    width="322"
                    height="322"
                  />
                </td>
                <td>
                  <img
                    src="static/images/cupcake.png"
                    alt="cupcake"
                    width="322"
                    height="322"
                  />
                </td>
              </tr>
              <tr>
                <td>
                  <img
                    src="static/images/party.png"
                    alt="party"
                    width="322"
                    height="322"
                  />
                </td>
                <td>
                  <img
                    src="static/images/rocets.png"
                    alt="rocets"
                    width="322"
                    height="322"
                  />
                </td>
                <td>
                  <img
                    src="static/images/book.png"
                    alt="book"
                    width="322"
                    height="322"
                  />
                </td>
              </tr>
              <tr>
                <td>
                  <img
                    src="static/images/park.jpg"
                    alt="park"
                    width="322"
                    height="322"
                  />
                </td>
                <td>
                  <img
                    src="static/images/two.jpg"
                    alt="two"
                    width="322"
                    height="322"
                  />
                </td>
                <td>
                  <img
                    src="static/images/pot.jpg"
                    alt="pot"
                    width="322"
                    height="322"
                  />
                </td>
              </tr>
            </table>
          </div>
        </td>
      </tr>
    </table>
  </body>
</html>
